# Change these first
owner: FptbbSystems # Your GitHub username
repo: Uptime # Your Github repository name

# Add your sites here
sites:
  - name: Fptbb.com
    url: https://fptbb.com
  - name: Ro-Brazil
    url: https://robr.page
  - name: Api Endpoint
    url: $API_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: up.fptbb.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://cdn.jsdelivr.net/gh/FptbbSystems/Uptime@master/fp.png
  name: FpUptime
  introTitle: "Estatisticas de boa parte dos meus sistemas, tudo aqui :D"
  introMessage: Caso tenha alguma duvido, entre em contato comigo diretamente via [Email](mailto:lucas@fptbb.com)
  navbar:
    - title: Status
      href: /
    - title: Essa Pagina
      href: https://github.com/$OWNER/$REPO
    - title: Meu Github
      href: https://github.com/fptbb

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
