# Change these first
owner: FptbbSystems # Your GitHub username
repo: Uptime # Your Github repository name
user-agent: fptbb
# Add your sites here
sites:
  - name: Fptbb.com
    url: https://fptbb.com/tempo
    __dangerous__insecure: true
  - name: Ro-Brazil
    url: https://robr.page/tempo
    __dangerous__insecure: true
  - name: Ro-Paste
    url: https://paste.robr.page
    __dangerous__insecure: true
  - name: Ro-Anime
    url: http://anime.fptbb.com
    __dangerous__insecure: true
  - name: Api Endpoint
    url: $API_SITE
    __dangerous__insecure: true

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: up.fptbb.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://cdn.jsdelivr.net/gh/FptbbSystems/Uptime@master/fp.png
  name: FpUptime
  introTitle: "Estatisticas de boa parte dos meus sistemas, tudo aqui :D"
  introMessage: Caso tenha alguma duvido, entre em contato comigo diretamente via [Email](mailto:lucas@fptbb.com)
  navbar:
    - title: Status
      href: /
    - title: Essa Pagina
      href: https://github.com/$OWNER/$REPO
    - title: Meu Github
      href: https://github.com/fptbb

i18n:
  activeIncidents: Incidentes Ativos
  allSystemsOperational: Todos os sistemas operacionais
  incidentReport: "Sobre o incidente numero #$NUMBER →"
  activeIncidentSummary: Aberto em $DATE com $POSTS posts
  incidentTitle: Incidente $NUMBER Detalhes
  incidentDetails: Detalhes do Incidente
  incidentFixed: Fixo
  incidentOngoing: Em Andamento
  incidentOpenedAt: Aberto as
  incidentClosedAt: Fechado as
  incidentSubscribe: Inscreva-se para atualizações
  incidentViewOnGitHub: Veja no Github
  incidentCommentSummary: Postado as $DATE por $AUTHOR
  incidentBack: ← Voltar para todos os Incidentes
  pastIncidents: Incidentes anteriores
  pastIncidentsResolved: Resolvido em $MINUTES minutos com $POSTS posts
  liveStatus: Status ao vivo
  overallUptime: "Uptime Geral: $UPTIME"
  overallUptimeTitle: Uptime Geral
  averageResponseTime: "Tempo de resposta medio: $TIMEms"
  averageResponseTimeTitle: Tempo de resposta medio
  sevelDayResponseTime: Tempo de resposta nos ultimos 7 dias
  responseTimeMs: Tempo de resposta (ms)
  up: Online
  down: Offline
  degraded: Quebrado
  ms: ms
  loading: Carregando
  navGitHub: GitHub
  footer: Essa pagina é de [codigo aberto]($REPO), criada com [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Uso da Api Excedido
  rateLimitExceededIntro: Tu excedeu o limite de uso desse site, tente novamente em algum tempo. Ou tente usar uma chave de api diferente do github.
  rateLimitExceededWhatDoesErrorMean: Oque esse erro significa?
  rateLimitExceededErrorMeaning: Esse site usa a api do github para manter estatisticas atualizadas dos sites, e permite 60 pedidos por ip, por minuto, tal quantidade que ja foi consumida.
  rateLimitExceededErrorHowCanFix: Como posso corrigir?
  rateLimitExceededErrorFix: Tu pode simplesmente esperar, em 1 hora o acesso sera liberado novamente, ou usar seu proprio token da api, e assim ter mais 1,500 pedidos por hora livres.
  rateLimitExceededGeneratePAT: Aprenda a gerar um novo token da api
  rateLimitExceededHasSet: Tu tem um token da api configurado.
  rateLimitExceededRemoveToken: Remover token
  rateLimitExceededGitHubPAT: Token de acesso pessoal Github
  rateLimitExceededCopyPastePAT: Copie e cole seu token
  rateLimitExceededSaveToken: Salvar token
  errorTitle: Um erro ocorreu
  errorIntro: Um erro ocorreu tentando achar os ultimos dados de status.
  errorText: Tu pode tentar em alguns momentos.
  errorHome: Ir para a pagina inicial

commitMessages:
  readmeContent: ":pencil: Resumo da atualização do Readme.md [skip ci] [upptime]"
  summaryJson: ":card_file_box: Resumo da atualização do Status [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME é $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Atualiza os Graficos [skip ci] [upptime]"
  commitAuthorName: "Fptbb Bot"
  commitAuthorEmail: "bot@fptbb.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
